server:
  port: 8888
management:
  security:
    enabled: false
spring:
  application:
     name: configserver
  cloud:
    config:
      server:
         git:
          uri: https://github.com/higherzjm/mynew2019
          search-paths: myconfig # 配置文件所在文件夹目录名称
          username: higherzjm
          password: Tf@123456


